[package]
name = "crossbeam_epoch_0_4_0"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
crossbeam-epoch = "0.4.0"
crossbeam-utils = "0.2.2"
lolbench_support = { path = "../../support" }

[dev-dependencies]
lolbench = { path = "../../" }
