[package]
name = "quickcheck_0_6_1"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
quickcheck = "0.6.1"
rand = "0.4.2"
lolbench_support = { path = "../../support" }

[dev-dependencies]
lolbench = { path = "../../" }
